/* V4: sikker backend til AU_AI_Spoergeskema_Svar. Faner: Svar + Adgang. */
const ANSWER_SHEET='Svar';
const ACCESS_SHEET='Adgang';
function doPost(e){const lock=LockService.getScriptLock();try{lock.waitLock(10000);const d=JSON.parse((e.postData&&e.postData.contents)||'{}');if(d.action!=='survey_save')return json_({ok:false,code:'BAD_ACTION'});return json_(saveSurvey_(d));}catch(err){return json_({ok:false,code:'SERVER_ERROR',message:String(err)});}finally{try{lock.releaseLock();}catch(_){}}}
function doGet(e){const p=e.parameter||{};let r={ok:false,code:'BAD_ACTION'};try{if(p.action==='survey_ping')r=ping_(p.token||'');else if(p.action==='survey_status')r=getSurveyStatus_(p.token||'',p.sessionId||'');}catch(err){r={ok:false,code:'SERVER_ERROR',message:String(err)};}return jsonp_(r,p.callback);}
function ping_(token){const a=findAccess_(String(token||''));return a.ok?{ok:true,protocol:4,mode:a.mode}:{ok:false,protocol:4,code:a.code};}
function saveSurvey_(d){const token=String(d.token||'').trim(),sid=String(d.sessionId||'').trim(),wanted=d.status==='completed'?'completed':'incomplete';if(!token||!sid)return {ok:false,code:'MISSING_ACCESS'};const a=authorize_(token,sid,wanted);if(!a.ok)return a;const sh=SpreadsheetApp.getActive().getSheetByName(ANSWER_SHEET);if(!sh)return {ok:false,code:'NO_ANSWER_SHEET'};const h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0],sidCol=h.indexOf('session_id')+1,statusCol=h.indexOf('status')+1;if(!sidCol||!statusCol)return {ok:false,code:'BAD_HEADERS'};let row=findRow_(sh,sidCol,sid);if(row&&String(sh.getRange(row,statusCol).getValue()||'')==='completed')return {ok:true,sessionId:sid,status:'completed',idempotent:true};if(!row)row=sh.getLastRow()+1;const now=new Date(),test=a.mode==='TEST'?'TEST - MÅ IKKE BRUGES':'NEJ - RIGTIG BESVARELSE';const vals=h.map(x=>{if(x==='session_id')return sid;if(x==='status')return wanted;if(x==='started_at')return d.startedAt?new Date(d.startedAt):now;if(x==='updated_at')return now;if(x==='completed_at')return wanted==='completed'?(d.completedAt?new Date(d.completedAt):now):'';if(x==='test_result')return test;if(x.endsWith('_other')){const k=x.slice(0,-6)+'_andet';return d[k]!==undefined?d[k]:'';}return d[x]!==undefined?d[x]:'';});sh.getRange(row,1,1,h.length).setValues([vals]);SpreadsheetApp.flush();return {ok:true,sessionId:sid,status:wanted,test:a.mode==='TEST'};}
function authorize_(token,sid,wanted){const a=findAccess_(token);if(!a.ok)return a;if(a.mode==='TEST')return a;const sh=a.sheet,row=a.row,c=a.cols,v=a.values,status=String(v[c.status]||'available'),bound=String(v[c.session]||'');if(status==='used')return bound===sid?{ok:true,mode:'NORMAL',row,alreadyUsed:true}:{ok:false,code:'TOKEN_USED'};if(bound&&bound!==sid)return {ok:false,code:'TOKEN_RESERVED'};if(!bound){sh.getRange(row,c.session+1).setValue(sid);sh.getRange(row,c.status+1).setValue('reserved');}if(wanted==='completed'){sh.getRange(row,c.status+1).setValue('used');sh.getRange(row,c.used+1).setValue(new Date());}return {ok:true,mode:'NORMAL',row};}
function findAccess_(token){const sh=SpreadsheetApp.getActive().getSheetByName(ACCESS_SHEET);if(!sh)return {ok:false,code:'NO_ACCESS_SHEET'};const all=sh.getDataRange().getValues(),h=all[0],c={token:h.indexOf('token'),mode:h.indexOf('mode'),status:h.indexOf('status'),session:h.indexOf('session_id'),used:h.indexOf('used_at')};if(Object.values(c).some(x=>x<0))return {ok:false,code:'BAD_ACCESS_HEADERS'};for(let i=1;i<all.length;i++)if(String(all[i][c.token])===token)return {ok:true,mode:String(all[i][c.mode]||'NORMAL').toUpperCase(),row:i+1,sheet:sh,cols:c,values:all[i]};return {ok:false,code:'INVALID_TOKEN'};}
function getSurveyStatus_(token,sid){if(!token||!sid)return {ok:false,code:'MISSING_ACCESS'};const a=findAccess_(token);if(!a.ok)return a;if(a.mode!=='TEST'&&String(a.values[a.cols.session]||'')!==sid)return {ok:false,code:'TOKEN_SESSION_MISMATCH'};const sh=SpreadsheetApp.getActive().getSheetByName(ANSWER_SHEET),h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0],s=h.indexOf('session_id')+1,st=h.indexOf('status')+1,u=h.indexOf('updated_at')+1,row=findRow_(sh,s,sid);if(!row)return {ok:false,code:'NOT_FOUND'};return {ok:true,sessionId:sid,status:String(sh.getRange(row,st).getValue()||''),updatedAt:String(sh.getRange(row,u).getDisplayValue()||''),test:a.mode==='TEST'};}
function findRow_(sh,col,value){if(!value||sh.getLastRow()<2)return 0;const f=sh.getRange(2,col,sh.getLastRow()-1,1).createTextFinder(value).matchEntireCell(true).findNext();return f?f.getRow():0;}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
function jsonp_(o,cb){const safe=/^[A-Za-z_$][0-9A-Za-z_$\.]*$/.test(String(cb||''))?String(cb):'';return safe?ContentService.createTextOutput(safe+'('+JSON.stringify(o)+');').setMimeType(ContentService.MimeType.JAVASCRIPT):json_(o);}
